[versions]
androidMinSdk = "23"
androidTargetSdk = "36"
androidCompileSdk = "36"

jvmTarget = "17"

libVersion = "1.5.0"

paletteKtx = "1.0.0"
detekt = "1.23.8"

kotlin = "2.3.10"
agp = "8.13.2"

composeBom = "2026.01.01"
material3 = "1.4.0"
coil = "2.7.0"

androidxCore = "1.17.0"
androidxLifecycle = "2.10.0"
desugaring = "2.1.5"
activityCompose = "1.12.3"

[libraries]
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }